---
- hosts: scanners
  become_method: sudo
  remote_user: remoteNosikow
  become: true

  tasks:
  - name: Install NMAP
    ansible.builtin.apt:
        name: nmap
        state: latest
        update_cache: true

  - name: Scan
    ansible.builtin.shell: "nmap {{ item }} -p 80 -oG -"
    loop: "{{ lookup('file', './targets.txt').splitlines() }}"
    register: scan_results

  - name: Scan results
    ansible.builtin.debug:
      msg: "{{ item.stdout_lines }}"
    loop: "{{ scan_results.results }}"
